name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Test library
        run: npm run test

      - name: Build
        run: npm run build

      - name: Configure git user info
        run: |
          git config user.name "Gor Sargsyan"
          git config user.email "gorsargsyanm@gmail.com"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
      # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
